import { site } from "../data/site.mjs";
import { external, icon, whatsappIcon } from "./layout.mjs";

const actionIcon = (name) => {
  const images = { careers: "kurosu-hub-careers.jpg", machinefinder: "kurosu-hub-machinefinder.jpg", official: "kurosu-hub-official.jpg" };
  return images[name] ? `<img src="/assets/images/${images[name]}" alt="" width="600" height="600" loading="lazy">` : name === "whatsapp" ? whatsappIcon() : icon(name);
};
const action = (name, text, href, primary = false, shape = "grid") => `<a class="ks-page__action${primary ? " ks-page__action--primary" : ""}" href="${href}"${href.startsWith("http") ? external : ""}><span class="ks-page__icon">${shape === "whatsapp" ? whatsappIcon() : icon(shape)}</span><span class="ks-page__action-copy"><h3>${name}</h3><p>${text}</p></span><span class="ks-page__arrow" aria-hidden="true">→</span></a>`;
const button = (label, href, light = false) => `<a class="ks-page__button${light ? " ks-page__button--light" : ""}" href="${href}"${href.startsWith("http") ? external : ""}>${href.includes("wa.me") ? whatsappIcon() : ""}<span>${label}</span></a>`;
const hero = (eyebrow, title, text, buttons = "") => `<section class="ks-page__hero"><span class="ks-page__eyebrow">${eyebrow}</span><h1>${title}</h1><p>${text}</p>${buttons ? `<div class="ks-page__button-row">${buttons}</div>` : ""}</section>`;

export function home() {
  const actions = site.actions.map((item, index) => `<a class="ks-action-card${index < 2 ? " ks-action-card--priority" : ""}" href="${item.href}"${item.external ? external : ""}><span class="ks-action-card__visual">${actionIcon(item.icon)}</span><span class="ks-action-card__copy"><strong>${item.name}</strong><small>${item.description}</small></span><span class="ks-action-card__arrow" aria-hidden="true">→</span></a>`).join("");
  const social = site.social.map(([name, href, id]) => `<a class="ks-social__link" href="${href}"${external} aria-label="${name}">${icon(id)}</a>`).join("");
  const videos = site.videos.map(([id, start, title, href]) => `<article class="ks-video-card"><div class="ks-video-card__player" data-ks-video data-video-id="${id}" data-video-start="${start}" data-video-title="${title}"><a class="ks-video-card__poster" href="${href}"${external} data-ks-video-trigger aria-label="Reproducir: ${title}"><img src="/assets/images/video-${id}.jpg" alt="" width="480" height="360" loading="lazy"><span class="ks-video-card__play">${icon("play")}</span></a></div><div class="ks-video-card__copy"><p class="ks-video-card__meta">Kurosu &amp; Cía. · YouTube</p><h3>${title}</h3><a class="ks-video-card__fallback" href="${href}"${external}>Abrir en YouTube</a></div></article>`).join("");
  return `<div class="ks-home"><section class="ks-home-hero"><picture class="ks-home-hero__media" aria-hidden="true"><source media="(min-width: 768px)" srcset="/assets/images/kurosu-hub-background-desktop.png"><img src="/assets/images/kurosu-hub-background-mobile.png" alt="" width="825" height="1466" fetchpriority="high"></picture><div class="ks-home-hero__shade" aria-hidden="true"></div><div class="ks-home__container ks-home-hero__content"><img class="ks-home-hero__profile" src="/assets/images/kurosu-hub-profile.jpg" width="480" height="480" alt="Sede de Kurosu &amp; Cía." fetchpriority="high"><p class="ks-home-hero__location">${icon("pin")} Paraguay</p><h1>Kurosu &amp; Cía.</h1><p class="ks-home-hero__tagline">Impulsando el progreso en Paraguay · Distribuidor John Deere</p><nav class="ks-social" aria-label="Redes sociales de Kurosu y Cía.">${social}</nav></div></section><div class="ks-home__body"><section class="ks-home__container ks-actions-section"><div class="ks-section-title"><p class="ks-section-title__eyebrow">Acceso directo</p><h2>¿Qué necesitás hoy?</h2></div><nav class="ks-action-list" aria-label="Accesos principales">${actions}</nav></section><section class="ks-home__container ks-videos-section"><div class="ks-section-title ks-section-title--videos"><p class="ks-section-title__eyebrow">Desde nuestro canal</p><h2>Historias y tecnología en acción</h2><p>Reproducí cada video cuando quieras, sin demorar la carga inicial.</p></div><div class="ks-video-list">${videos}</div></section></div></div>`;
}

export function contact() { return `<section class="ks-page"><div class="ks-page__container">${hero("Contacto", "Estamos para ayudarte", "Elegí un canal directo para consultas sobre equipos, servicio técnico o promociones.")}<section class="ks-page__section"><h2>Canales de atención</h2><div class="ks-page__grid ks-page__grid--two">${action("WhatsApp 24 hs", "Atención directa de Kurosu.", site.whatsapp, true, "whatsapp")}${action("Canal de WhatsApp", "Novedades y comunicaciones.", "https://whatsapp.com/channel/0029VbAWgm77z4kk4LJ1MZ1o", false, "whatsapp")}${action("Sitio oficial", "Conocé más sobre Kurosu.", site.official, false, "globe")}</div></section></div></section>`; }

export function products() { const cards = site.products.map(([name, text, href]) => action(name, text, href, false, "grid")).join(""); return `<section class="ks-page"><div class="ks-page__container">${hero("Productos John Deere", "Encontrá información para tu equipo", "Accedé a las categorías oficiales de John Deere y consultanos si necesitás orientación.", button("Consultar por WhatsApp", site.whatsapp))}<section class="ks-page__section"><h2>Explorá por categoría</h2><div class="ks-page__grid ks-page__grid--two">${cards}</div></section></div></section>`; }

export function support() { return `<section class="ks-page"><div class="ks-page__container">${hero("Soporte técnico", "¿Necesitás ayuda con tu equipo?", "Contactá al equipo de Kurosu para asistencia y consultá los recursos oficiales de John Deere.", button("Hablar por WhatsApp", site.whatsapp))}<section class="ks-page__section"><h2>Accesos de asistencia</h2><div class="ks-page__grid ks-page__grid--two">${action("Asistencia técnica", "Escribinos para recibir atención.", site.whatsapp, true, "whatsapp")}${action("Servicio especializado", "Información oficial de servicio Kurosu.", site.products[2][2], false, "service")}${action("Canales de contacto", "Elegí el canal que prefieras.", "/contacto/", false, "mail")}${action("Preguntas frecuentes", "Respuestas rápidas del portal.", "/preguntas-frecuentes/", false, "help")}</div></section></div></section>`; }

export function promotions() { return `<section class="ks-page"><div class="ks-page__container">${hero("Promociones", "Consultá las oportunidades vigentes", "Las condiciones y la disponibilidad se confirman directamente con Kurosu.", button("Consultar por WhatsApp", site.whatsapp))}<section class="ks-page__section"><div class="ks-page__empty"><h2>¿Buscás un equipo o servicio?</h2><p>Escribinos con lo que necesitás para conocer las alternativas disponibles.</p></div></section></div></section>`; }

export function faq() { const faqs = [["¿Dónde veo productos John Deere?", "En <a href=\"/enlaces-de-productos/\">Productos</a> encontrás los enlaces oficiales por categoría."], ["¿Cómo solicito asistencia técnica?", `Escribinos por <a href="${site.whatsapp}"${external}>WhatsApp</a> o visitá <a href="/soporte-tecnico/">Soporte técnico</a>.`], ["¿Dónde consulto por repuestos?", `Usá el acceso de <a href="${site.products[2][2]}"${external}>servicio especializado Kurosu</a> o escribinos por WhatsApp.`], ["¿Cómo conozco las promociones vigentes?", "Visitá <a href=\"/promociones/\">Promociones</a> y consultá las condiciones directamente con Kurosu."], ["¿Dónde encuentro los canales de contacto?", "En <a href=\"/contacto/\">Contacto</a> están los canales oficiales disponibles."]].map(([q,a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join(""); return `<section class="ks-page" aria-labelledby="faq-title"><div class="ks-page__container">${hero("Preguntas frecuentes", "Respuestas rápidas", "Encontrá el acceso adecuado para productos, soporte y consultas.")}<section class="ks-page__section" aria-label="Preguntas y respuestas"><div class="ks-page__grid">${faqs}</div></section></div></section>`; }

export function about() { return `<section class="ks-page"><div class="ks-page__container">${hero("Kurosu &amp; Cía.", "Más de cinco décadas junto al desarrollo productivo del Paraguay", "Kurosu &amp; Cía. inició sus actividades en Encarnación en 1968 y, desde 1975, opera bajo su actual denominación. La información institucional se mantiene en su sitio oficial.", `${button("Conocer la historia de Kurosu", "https://www.kurosu.com.py/index.php/content/about_us")}${button("Ver ubicaciones", "https://www.kurosu.com.py/location", true)}`)}<section class="ks-page__section"><h2>Información útil para clientes</h2><div class="ks-page__grid ks-page__grid--two">${action("Equipos y soluciones", "Accedé a las categorías oficiales de productos de Kurosu.", "/enlaces-de-productos/", false, "grid")}${action("Servicio y asistencia", "Encontrá soporte técnico y recursos oficiales.", "/soporte-tecnico/", false, "service")}${action("Sucursales y horarios", "Consultá ubicaciones, teléfonos y horarios de atención.", "https://www.kurosu.com.py/location", false, "pin")}${action("Contacto directo", "Elegí el canal que mejor se adapte a tu consulta.", "/contacto/", false, "mail")}</div></section></div></section>`; }

export function search() { return `<section class="ks-page section-landing-search"><div class="container"><h1>Buscar</h1><form class="ks-search-form" role="search"><label class="sr-only" for="searchInput">Buscar en el portal</label><div class="input-group"><input id="searchInput" class="form-control" data-ks-search-input data-ks-search-results-id="searchResults" type="search" name="q" placeholder="Buscar productos, soporte o contacto" autocomplete="off"><span class="input-group-btn"><button class="btn btn-primary ks-search-submit" type="submit" aria-label="Buscar">${icon("search")}</button></span></div></form><div id="searchResults" class="ks-search-results" aria-live="polite"></div></div></section>`; }

export function message(kind) { const notFound = kind === "404"; return `<section class="ks-page"><div class="ks-page__container"><section class="ks-page__empty"><span class="ks-page__eyebrow">${notFound ? "Error 404" : "Acceso restringido"}</span><h1>${notFound ? "No encontramos esta página" : "No tenés acceso a esta página"}</h1><p>${notFound ? "Puede que el enlace haya cambiado o ya no esté disponible." : "Volvé al inicio o contactanos si necesitás ayuda."}</p><div class="ks-page__button-row">${button("Ir al inicio", "/")}${button("Contacto", "/contacto/")}</div></section></div></section>`; }
